version: '3.9'
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   restart: unless-stopped
  #   depends_on:
  #     - api
  #   networks:
  #     - nginx-network
  api:
    build:
      context: "./eegs-back-end"
      dockerfile: Dockerfile
    ports:
      - 4000:52769
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge